site_name: 'Takahiro Ueda''s page'
site_author: 'Takahiro Ueda'
copyright: '&copy; 2019 Takahiro Ueda'

nav:
  - Home: index.md
  - CV: cv.md
  - Publications: publications.md
  - Talks: talks.md

theme: material

extra:
  logo:
    icon: 'home'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  social:
    - type: 'github'
      link: 'https://github.com/tueda'

markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.smarty
  - pymdownx.arithmatex:
      generic: true
  - mdx_bibtex

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css
  - css/extra.css

extra_javascript:
  - js/eads-start.js
  - https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/contrib/auto-render.min.js
  - js/katex-start.js
