site_name: 'Takahiro Ueda''s page'
site_author: 'Takahiro Ueda'
copyright: '&copy; 2020 Takahiro Ueda'

nav:
  - Home: index.md
  - CV: cv.md
  - Publications: publications.md
  - Talks: talks.md
  - Software: software.md
  - Misc: misc.md

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: indigo
    accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tueda
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0001-9805-5832
    - icon: academicons/inspire
      link: https://inspirehep.net/authors/1032372
    - icon: academicons/google-scholar
      link: https://scholar.google.com/citations?user=zrbJjwUAAAAJ

markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.smarty
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
  - mdx_bibtex

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css
  - css/extra.css

extra_javascript:
  - js/eads-start.js
  - https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js
  - js/katex-start.js
