site_name: 'Takahiro Ueda''s page'
site_author: 'Takahiro Ueda'
copyright: '&copy; 2018 Takahiro Ueda'

pages:
  - Home: index.md
  - CV: cv.md
  - Publications: publications.md
  - Talks: talks.md

theme: material

extra:
  logo:
    icon: 'home'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  social:
    - type: 'github'
      link: 'https://github.com/tueda'

markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.smarty
  - pymdownx.arithmatex:
      generic: true
  - bibtex

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
  - css/extra.css

extra_javascript:
  - js/eads-start.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js
  - js/katex-start.js
