[tool.poetry]
name = "tueda.github.io"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.6"

bibtexparser = "^1.2.0"
markdown-include = "^0.6.0"
mkdocs = "^1.2.3"
mkdocs-material = "^7.3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
