[tool.poetry]
name = "tueda.github.io"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.5"

bibtexparser = "^1.2.0"
markdown-include = "^0.5.1"
mkdocs = "^1.1.2"
mkdocs-material = "^5.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
